# Generated by Django 6.0.4 on 2026-05-02 17:41

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_client_client_id_alter_client_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, default=api.models.generate_invoice_number, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_id',
            field=models.CharField(blank=True, default=api.models.generate_po_id, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotation_id',
            field=models.CharField(blank=True, default=api.models.generate_quotation_id, max_length=50, unique=True),
        ),
    ]
